export const SET_OBJECTS = "SET_OBJECTS";
export const SET_CURRENT_OBJECT_TYPE = "SET_CURRENT_OBJECT_TYPE";
export const SET_CURRENT_ACTION_TYPE = "SET_CURRENT_ACTION_TYPE";
export const SET_COLOR = "SET_COLOR";
export const SET_STROKE = "SET_STROKE";
export const SET_SELECTED_OBJECT_IDS = "SET_SELECTED_OBJECT_IDS";
export const SET_HISTORY = "SET_HISTORY";
export const SET_FUTURE = "SET_FUTURE";
